import {
  AlertTriangle,
  BarChart3,
  BookOpen,
  Calendar,
  Check,
  Clock3,
  Compass,
  Gift,
  GraduationCap,
  Image as ImageIcon,
  Laptop,
  Layers,
  LayoutGrid,
  Lightbulb,
  type LucideIcon,
  Radar,
  RefreshCw,
  SearchCheck,
  ShieldCheck,
  Sprout,
  Target,
  TrendingUp,
  Users,
  LineChart,
  ListChecks,
  Wallet,
  Zap,
} from "lucide-react";
import type { IconKey } from "@/config/content";

/**
 * Registro central de ícones. Os dados de conteúdo (src/config/content.ts)
 * referenciam ícones por chave (string) — este mapa resolve a chave para
 * o componente real, mantendo os arquivos de conteúdo livres de JSX.
 */
export const ICONS: Record<IconKey, LucideIcon> = {
  "book-open": BookOpen,
  zap: Zap,
  "bar-chart": BarChart3,
  laptop: Laptop,
  radar: Radar,
  "search-check": SearchCheck,
  "line-chart": LineChart,
  "list-checks": ListChecks,
  clock: Clock3,
  wallet: Wallet,
  "calendar-clock": Calendar,
  "alert-triangle": AlertTriangle,
  lightbulb: Lightbulb,
  sprout: Sprout,
  "layout-grid": LayoutGrid,
  "graduation-cap": GraduationCap,
  compass: Compass,
  target: Target,
  image: ImageIcon,
  layers: Layers,
  "trending-up": TrendingUp,
  "shield-check": ShieldCheck,
  users: Users,
  "refresh-cw": RefreshCw,
  gift: Gift,
  check: Check,
};
